from django.db import models

# Create your models here.
class Student(models.Model):
    student_id = models.TextField(blank=True, null=True)
    sr_no = models.TextField(unique=True) 
    name = models.TextField(blank=True, null=True)
    gender = models.TextField(blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    religion = models.TextField(blank=True, null=True)
    place_of_birth = models.TextField(blank=True, null=True)
    mother_tongue = models.TextField(blank=True, null=True)
    admission_no = models.TextField(blank=True, null=True)
    university_reg_no = models.TextField(blank=True, null=True)
    nationality = models.TextField(blank=True, null=True)
    caste = models.TextField(blank=True, null=True)
    blood_group = models.TextField(blank=True, null=True)
    aadhaar_no = models.TextField(blank=True, null=True)
    abc_id = models.TextField(blank=True, null=True)
    mark1 = models.TextField(blank=True, null=True)
    mark2 = models.TextField(blank=True, null=True)
    academic_year = models.TextField(blank=True, null=True)
    admitted_category = models.TextField(blank=True, null=True)
    entrance_rank = models.TextField(blank=True, null=True)
    community = models.TextField(blank=True, null=True)
    date_of_admission = models.DateField(blank=True, null=True)
    admission_quota = models.TextField(blank=True, null=True)
    admission_type = models.TextField(blank=True, null=True)
    eligible_category = models.TextField(blank=True, null=True)
    entrance_roll_no = models.TextField(blank=True, null=True)
    nata_score = models.TextField(blank=True, null=True)
    father_name = models.TextField(blank=True, null=True)
    mother_name = models.TextField(blank=True, null=True)
    father_mobile = models.TextField(blank=True, null=True)
    mother_mobile = models.TextField(blank=True, null=True)
    email = models.TextField(blank=True, null=True)
    father_occupation = models.TextField(blank=True, null=True)
    mother_occupation = models.TextField(blank=True, null=True)
    phone_office = models.TextField(blank=True, null=True)
    annual_income = models.TextField(blank=True, null=True)
    house_name = models.TextField(blank=True, null=True)
    street = models.TextField(blank=True, null=True)
    street2 = models.TextField(blank=True, null=True)
    district = models.TextField(blank=True, null=True)
    pin = models.TextField(blank=True, null=True)
    state = models.TextField(blank=True, null=True)
    bank_name = models.TextField(blank=True, null=True)
    branch = models.TextField(blank=True, null=True)
    account_no = models.TextField(blank=True, null=True)
    ifsc_code = models.TextField(blank=True, null=True)
    user_name = models.TextField(blank=True, null=True) 
    parent_user_name = models.TextField(blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    default_password = models.TextField(blank=True, null=True)
    parent_default_pwd = models.TextField(blank=True, null=True)
    department = models.TextField(blank=True, null=True)
    Instagram_id = models.CharField(max_length=45, blank=True, null=True)
    opt_out = models.BooleanField(default=False)
    contributed_ig = models.CharField(max_length=45, blank=True, null=True)
    contributor = models.TextField(blank=True, null=True)
    instagram_pk = models.CharField(max_length=45, blank=True, null=True)
    phone = models.TextField(blank=True, null=True)
    

    class Meta:
        db_table = 'students'