# Generated by Django 5.2.1 on 2025-06-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("silkApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="contributed_ig",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="contributed_ph",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="contributor",
            field=models.TextField(blank=True, null=True),
        ),
    ]
