# Generated by Django 4.2.7 on 2025-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("silkApi", "0002_student_contributed_ig_student_contributed_ph_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="contributed_ph",
        ),
        migrations.AlterField(
            model_name="student",
            name="Instagram_id",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="contributed_ig",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
