# Generated by Django 5.2.3 on 2025-06-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silkApi', '0003_remove_student_contributed_ph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='instagram_pk',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
